package com.mutistic.mybatis.generate.model;

import java.util.Date;

public class BizUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.id_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.name_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.account_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.password_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.mobile_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.status_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.create_by
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.create_time
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.update_by
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.update_time
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.remark_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.enable_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Byte enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.version_no
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    private Integer versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.id_
     *
     * @return the value of biz_user.id_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.id_
     *
     * @param id the value for biz_user.id_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.name_
     *
     * @return the value of biz_user.name_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.name_
     *
     * @param name the value for biz_user.name_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.account_
     *
     * @return the value of biz_user.account_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.account_
     *
     * @param account the value for biz_user.account_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.password_
     *
     * @return the value of biz_user.password_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.password_
     *
     * @param password the value for biz_user.password_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.mobile_
     *
     * @return the value of biz_user.mobile_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.mobile_
     *
     * @param mobile the value for biz_user.mobile_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.status_
     *
     * @return the value of biz_user.status_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.status_
     *
     * @param status the value for biz_user.status_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.create_by
     *
     * @return the value of biz_user.create_by
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.create_by
     *
     * @param createBy the value for biz_user.create_by
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.create_time
     *
     * @return the value of biz_user.create_time
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.create_time
     *
     * @param createTime the value for biz_user.create_time
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.update_by
     *
     * @return the value of biz_user.update_by
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.update_by
     *
     * @param updateBy the value for biz_user.update_by
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.update_time
     *
     * @return the value of biz_user.update_time
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.update_time
     *
     * @param updateTime the value for biz_user.update_time
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.remark_
     *
     * @return the value of biz_user.remark_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.remark_
     *
     * @param remark the value for biz_user.remark_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.enable_
     *
     * @return the value of biz_user.enable_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.enable_
     *
     * @param enable the value for biz_user.enable_
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.version_no
     *
     * @return the value of biz_user.version_no
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.version_no
     *
     * @param versionNo the value for biz_user.version_no
     *
     * @mbg.generated Fri Jan 25 14:12:10 CST 2019
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
}